const doctors = [
  {
    id: 1,
    name: "Dr. John Doe",
    specialty: "Cardiologist",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    experience: "15 years",
    fee: 150,
    bio: "Dr. John Doe is a renowned cardiologist with over 15 years of experience in treating heart conditions and performing cardiac procedures.",
  },
  {
    id: 2,
    name: "Dr. Sarah Smith",
    specialty: "Dermatologist",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    experience: "10 years",
    fee: 100,
    bio: "Dr. Sarah Smith specializes in treating skin conditions and provides comprehensive dermatological care for patients of all ages.",
  },
  {
    id: 3,
    name: "Dr. Michael Lee",
    specialty: "Neurologist",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    experience: "12 years",
    fee: 175,
    bio: "Dr. Michael Lee is an expert in neurological disorders, with special interests in migraine, epilepsy, and movement disorders.",
  },
  {
    id: 4,
    name: "Dr. Emily Chen",
    specialty: "Pediatrician",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    experience: "8 years",
    fee: 90,
    bio: "Dr. Emily Chen is a board-certified pediatrician dedicated to providing comprehensive care for infants, children, and adolescents.",
  },
  {
    id: 5,
    name: "Dr. Robert Wilson",
    specialty: "Orthopedic Surgeon",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    experience: "20 years",
    fee: 200,
    bio: "Dr. Robert Wilson specializes in sports medicine, joint replacement, and minimally invasive orthopedic procedures.",
  },
  {
    id: 6,
    name: "Dr. Lisa Anderson",
    specialty: "Gynecologist",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    experience: "14 years",
    fee: 120,
    bio: "Dr. Lisa Anderson provides comprehensive women's health care, including prenatal care, fertility treatments, and gynecological surgery.",
  },
  {
    id: 7,
    name: "Dr. David Martinez",
    specialty: "Ophthalmologist",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    experience: "11 years",
    fee: 130,
    bio: "Dr. David Martinez specializes in eye care, including cataract surgery, LASIK, and treatment of retinal diseases.",
  },
  {
    id: 8,
    name: "Dr. Jennifer Taylor",
    specialty: "Psychiatrist",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    experience: "9 years",
    fee: 140,
    bio: "Dr. Jennifer Taylor is a psychiatrist specializing in anxiety, depression, and mood disorders with a holistic approach to mental health.",
  },
  {
    id: 9,
    name: "Dr. James Brown",
    specialty: "Gastroenterologist",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    experience: "16 years",
    fee: 160,
    bio: "Dr. James Brown specializes in digestive disorders and performs advanced endoscopic procedures for diagnosis and treatment.",
  },
  {
    id: 10,
    name: "Dr. Maria Garcia",
    specialty: "Endocrinologist",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    experience: "13 years",
    fee: 145,
    bio: "Dr. Maria Garcia focuses on hormonal disorders, diabetes management, and thyroid conditions with personalized treatment plans.",
  },
  {
    id: 11,
    name: "Dr. William Davis",
    specialty: "Urologist",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    experience: "18 years",
    fee: 170,
    bio: "Dr. William Davis specializes in urinary tract conditions and men's health, including prostate care and kidney stone treatment.",
  },
  {
    id: 12,
    name: "Dr. Sophia Johnson",
    specialty: "Oncologist",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    experience: "17 years",
    fee: 190,
    bio: "Dr. Sophia Johnson is a compassionate oncologist specializing in various cancers with cutting-edge treatment protocols.",
  },
  {
    id: 13,
    name: "Dr. Thomas White",
    specialty: "Pulmonologist",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
    experience: "12 years",
    fee: 155,
    bio: "Dr. Thomas White specializes in respiratory conditions, including asthma, COPD, and sleep disorders.",
  },
  {
    id: 14,
    name: "Dr. Amanda Clark",
    specialty: "Rheumatologist",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
    experience: "10 years",
    fee: 135,
    bio: "Dr. Amanda Clark specializes in autoimmune diseases, arthritis, and other musculoskeletal and rheumatic diseases.",
  },
];

export default doctors;